# Generated by Django 4.0.3 on 2022-03-08 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_excerpt_remove_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='last_name',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='email_address',
            new_name='emailAddress',
        ),
    ]
